[package]
name = "thr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin_hashes = "0.14.0"
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_6"] }
